apiVersion: v1
kind: Service
metadata:
  name: graph-processing-agent
  labels:
    app: graph-processing-agent
spec:
  type: NodePort
  selector:
    app: graph-processing-agent
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
